/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package analyzer;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;

/**
 *
 * @author jgriebel
 */
public class AnalyzerWindow extends javax.swing.JFrame {

    /**
     * Creates new form AnalyzerWindow
     */
    public AnalyzerWindow() {
        analyzer = new Analyzer();
        projectThemesArray = new ArrayList<Theme>();
        initComponents();
        Scanner inStream = null;
        //Remove the hardcoding of themes.txt here
        //Eventually set this up so that it will load it from the project file
        try {
            inStream = new Scanner(new File("themes.txt"));
            while(inStream.hasNext()){
            String line = inStream.nextLine();
            String[] tmp = line.split(";");
            Theme t = new Theme(tmp[0]);
            
            for(String s: tmp[1].split(","))
                t.addKeyword(new Keyword(s));
            t.setColor(Integer.parseInt(tmp[2]));
            
            projectThemesArray.add(t);
            projectListModel.addElement(t);
            }
        } catch (FileNotFoundException ex) {
           themesMissing.setVisible(true);
        }
        //This seems janky. Surely there's a cleaner way to do this
       
        
        projectThemesList.setModel(projectListModel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openFileChooser = new javax.swing.JFileChooser(System.getProperty("user.dir"))
        ;
        themeManager = new javax.swing.JFrame();
        projectThemes = new javax.swing.JLabel();
        selectedThemes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        projectThemesList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        selectedThemesList = new javax.swing.JList();
        selectThemeButton = new javax.swing.JButton();
        removeButtonTheme = new javax.swing.JButton();
        themeNameLabel = new javax.swing.JLabel();
        keywordsLabel = new javax.swing.JLabel();
        themeField = new javax.swing.JTextField();
        keywordField = new javax.swing.JTextField();
        newThemeButton = new javax.swing.JButton();
        deleteThemeButton = new javax.swing.JButton();
        acceptThemesButton = new javax.swing.JButton();
        editThemeButton = new javax.swing.JButton();
        themesMissing = new javax.swing.JDialog();
        error1 = new javax.swing.JLabel();
        error2 = new javax.swing.JLabel();
        okErrorButton = new javax.swing.JButton();
        newThemeFrame = new javax.swing.JFrame();
        nameLabel = new javax.swing.JLabel();
        keyLabel = new javax.swing.JLabel();
        newThemeText = new javax.swing.JTextField();
        newKeywordText = new javax.swing.JTextField();
        reminderLabel = new javax.swing.JLabel();
        saveNewThemeButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        fileNotFoundException = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        editThemeFrame = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        editThemeText = new javax.swing.JTextField();
        editKeywordsText = new javax.swing.JTextField();
        saveChangesButton = new javax.swing.JButton();
        cancelChangesButton = new javax.swing.JButton();
        browseButton = new javax.swing.JButton();
        analyzeFiles = new javax.swing.JTextField();
        analyzeLabel = new javax.swing.JLabel();
        outputLabel = new javax.swing.JLabel();
        outputFile = new javax.swing.JTextField();
        analyzeButton = new javax.swing.JButton();
        themesButton = new javax.swing.JButton();

        openFileChooser.setDialogTitle("Select Files to Analyze");
        openFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileChooserActionPerformed(evt);
            }
        });

        themeManager.setTitle("Theme Manager");
        themeManager.setMinimumSize(new java.awt.Dimension(450, 375));

        projectThemes.setText("Project Themes:");

        selectedThemes.setText("Selected Themes:");

        projectThemesList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        projectThemesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                projectThemesListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(projectThemesList);

        jScrollPane2.setViewportView(selectedThemesList);

        selectThemeButton.setMnemonic('S');
        selectThemeButton.setText("Select");
        selectThemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectThemeButtonActionPerformed(evt);
            }
        });

        removeButtonTheme.setMnemonic('R');
        removeButtonTheme.setText("Remove");
        removeButtonTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonThemeActionPerformed(evt);
            }
        });

        themeNameLabel.setText("Theme:");

        keywordsLabel.setText("Keywords:");

        newThemeButton.setMnemonic('N');
        newThemeButton.setText("New");
        newThemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newThemeButtonActionPerformed(evt);
            }
        });

        deleteThemeButton.setMnemonic('D');
        deleteThemeButton.setText("Delete");
        deleteThemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteThemeButtonActionPerformed(evt);
            }
        });

        acceptThemesButton.setMnemonic('A');
        acceptThemesButton.setText("Accept");
        acceptThemesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptThemesButtonActionPerformed(evt);
            }
        });

        editThemeButton.setMnemonic('E');
        editThemeButton.setText("Edit");
        editThemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editThemeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout themeManagerLayout = new javax.swing.GroupLayout(themeManager.getContentPane());
        themeManager.getContentPane().setLayout(themeManagerLayout);
        themeManagerLayout.setHorizontalGroup(
            themeManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(themeManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(themeManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(themeManagerLayout.createSequentialGroup()
                        .addComponent(newThemeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editThemeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteThemeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acceptThemesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(themeManagerLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(keywordsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(keywordField))
                    .addGroup(themeManagerLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(themeNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(themeField))
                    .addGroup(themeManagerLayout.createSequentialGroup()
                        .addGroup(themeManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(projectThemes)
                            .addGroup(themeManagerLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(themeManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectThemeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(removeButtonTheme))))
                        .addGap(18, 18, 18)
                        .addGroup(themeManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectedThemes)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        themeManagerLayout.setVerticalGroup(
            themeManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(themeManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(themeManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectThemes)
                    .addComponent(selectedThemes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(themeManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(themeManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(themeManagerLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(selectThemeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeButtonTheme)))
                .addGap(18, 18, 18)
                .addGroup(themeManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themeNameLabel)
                    .addComponent(themeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(themeManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keywordsLabel)
                    .addComponent(keywordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(themeManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newThemeButton)
                    .addComponent(deleteThemeButton)
                    .addComponent(acceptThemesButton)
                    .addComponent(editThemeButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        themesMissing.setTitle("Themes File Missing");

        error1.setText("Error: Could not open the themes file.");

        error2.setText(" It may have been deleted or moved.");

        okErrorButton.setText("OK");
        okErrorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okErrorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout themesMissingLayout = new javax.swing.GroupLayout(themesMissing.getContentPane());
        themesMissing.getContentPane().setLayout(themesMissingLayout);
        themesMissingLayout.setHorizontalGroup(
            themesMissingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(themesMissingLayout.createSequentialGroup()
                .addGroup(themesMissingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(themesMissingLayout.createSequentialGroup()
                        .addGroup(themesMissingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(themesMissingLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(error1))
                            .addGroup(themesMissingLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(okErrorButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, themesMissingLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(error2)))
                .addContainerGap())
        );
        themesMissingLayout.setVerticalGroup(
            themesMissingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(themesMissingLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(error1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(error2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okErrorButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        newThemeFrame.setTitle("Create a New Theme");
        newThemeFrame.setAlwaysOnTop(true);
        newThemeFrame.setMinimumSize(new java.awt.Dimension(450, 135));

        nameLabel.setText("Name:");

        keyLabel.setText("Keywords:");

        reminderLabel.setText("Remember: Place commas between each keyword, and don't use spaces.");

        saveNewThemeButton.setMnemonic('S');
        saveNewThemeButton.setText("Save");
        saveNewThemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNewThemeButtonActionPerformed(evt);
            }
        });

        cancelButton.setMnemonic('C');
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newThemeFrameLayout = new javax.swing.GroupLayout(newThemeFrame.getContentPane());
        newThemeFrame.getContentPane().setLayout(newThemeFrameLayout);
        newThemeFrameLayout.setHorizontalGroup(
            newThemeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newThemeFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newThemeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(newThemeFrameLayout.createSequentialGroup()
                        .addComponent(reminderLabel)
                        .addContainerGap(59, Short.MAX_VALUE))
                    .addGroup(newThemeFrameLayout.createSequentialGroup()
                        .addGroup(newThemeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(keyLabel)
                            .addComponent(nameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(newThemeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newThemeText, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(newKeywordText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(newThemeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(saveNewThemeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addGap(89, 89, 89))))
        );
        newThemeFrameLayout.setVerticalGroup(
            newThemeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newThemeFrameLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(newThemeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(newThemeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveNewThemeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newThemeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newThemeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(keyLabel)
                        .addComponent(newKeywordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cancelButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reminderLabel))
        );

        jLabel1.setText("Error: A file could not be found.");

        jButton1.setMnemonic('O');
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fileNotFoundExceptionLayout = new javax.swing.GroupLayout(fileNotFoundException.getContentPane());
        fileNotFoundException.getContentPane().setLayout(fileNotFoundExceptionLayout);
        fileNotFoundExceptionLayout.setHorizontalGroup(
            fileNotFoundExceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileNotFoundExceptionLayout.createSequentialGroup()
                .addGroup(fileNotFoundExceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fileNotFoundExceptionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(fileNotFoundExceptionLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fileNotFoundExceptionLayout.setVerticalGroup(
            fileNotFoundExceptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileNotFoundExceptionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editThemeFrame.setTitle("Edit a Theme");
        editThemeFrame.setMinimumSize(new java.awt.Dimension(300, 150));

        jLabel2.setText("Theme:");

        jLabel3.setText("Keywords:");

        editThemeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editThemeTextActionPerformed(evt);
            }
        });

        saveChangesButton.setMnemonic('S');
        saveChangesButton.setText("Save");
        saveChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesButtonActionPerformed(evt);
            }
        });

        cancelChangesButton.setMnemonic('C');
        cancelChangesButton.setText("Cancel");

        javax.swing.GroupLayout editThemeFrameLayout = new javax.swing.GroupLayout(editThemeFrame.getContentPane());
        editThemeFrame.getContentPane().setLayout(editThemeFrameLayout);
        editThemeFrameLayout.setHorizontalGroup(
            editThemeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editThemeFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editThemeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(editThemeFrameLayout.createSequentialGroup()
                        .addGroup(editThemeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editThemeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editThemeText)
                            .addComponent(editKeywordsText, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                    .addGroup(editThemeFrameLayout.createSequentialGroup()
                        .addComponent(saveChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(cancelChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editThemeFrameLayout.setVerticalGroup(
            editThemeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editThemeFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editThemeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(editThemeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editThemeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(editKeywordsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editThemeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveChangesButton)
                    .addComponent(cancelChangesButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Westminster College Document Analyzer");
        setName("mainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(375, 175));

        browseButton.setMnemonic('B');
        browseButton.setText("Browse");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        analyzeFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyzeFilesActionPerformed(evt);
            }
        });

        analyzeLabel.setText("Analyze:");

        outputLabel.setText("Output:");

        outputFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputFileActionPerformed(evt);
            }
        });

        analyzeButton.setMnemonic('A');
        analyzeButton.setText("Analyze");
        analyzeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyzeButtonActionPerformed(evt);
            }
        });

        themesButton.setMnemonic('T');
        themesButton.setText("Themes");
        themesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(analyzeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(outputLabel))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(outputFile, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(analyzeFiles))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(themesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(analyzeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(browseButton)
                    .addComponent(analyzeFiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(analyzeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputLabel)
                    .addComponent(outputFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themesButton)
                    .addComponent(analyzeButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void analyzeFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzeFilesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_analyzeFilesActionPerformed

    private void outputFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputFileActionPerformed

    private void analyzeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzeButtonActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        analyzeButton.setEnabled(false);
       
        try {
            analyzer.analyze(outputFile.getText());
        } catch (FileNotFoundException ex) {
            fileNotFoundException.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(AnalyzerWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        analyzeButton.setEnabled(true);
    }//GEN-LAST:event_analyzeButtonActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
      openFileChooser.setMultiSelectionEnabled(true);
     
      int returnVal= openFileChooser.showOpenDialog(this);
      if(returnVal==JFileChooser.APPROVE_OPTION){
          File[] files = openFileChooser.getSelectedFiles();
          String s = "";
          for(File f: files){
              analyzer.addFile(f);
              s+="\""+f.getName()+"\"";
          }
          analyzeFiles.setText(s);
      }
    }//GEN-LAST:event_browseButtonActionPerformed

    private void openFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openFileChooserActionPerformed

    private void themesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themesButtonActionPerformed
        themeManager.setVisible(true);
    }//GEN-LAST:event_themesButtonActionPerformed

    private void okErrorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okErrorButtonActionPerformed
        themesMissing.setVisible(false);
    }//GEN-LAST:event_okErrorButtonActionPerformed

    private void selectThemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectThemeButtonActionPerformed

        int[] indices = projectThemesList.getSelectedIndices();
        ArrayList<Theme> toAdd = new ArrayList<Theme>();
        selectedListModel = new DefaultListModel();
        
        for(int i=0;i<indices.length;i++){
            //We have to use this convuluted statement to get the index of the theme
            //we want because we can't cast an object to a theme
            int index = projectThemesArray.indexOf(projectThemesList.getModel().getElementAt(i));
            Theme t = projectThemesArray.get(index);
            toAdd.add(t);
            selectedListModel.addElement(t);
        }
        selectedThemesList.setModel(selectedListModel);
    }//GEN-LAST:event_selectThemeButtonActionPerformed

    private void removeButtonThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonThemeActionPerformed
        List toRemove = selectedThemesList.getSelectedValuesList();
        
        for(Object s: toRemove){
            selectedListModel.removeElement(s);
        }
        selectedThemesList.setModel(selectedListModel);
    }//GEN-LAST:event_removeButtonThemeActionPerformed

    private void newThemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newThemeButtonActionPerformed
       newThemeFrame.setVisible(true);
    }//GEN-LAST:event_newThemeButtonActionPerformed

    private void projectThemesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_projectThemesListValueChanged
        if(projectThemesList.getSelectedValue()!=null){
            int index=projectThemesArray.indexOf(projectThemesList.getSelectedValue());
            Theme t = projectThemesArray.get(index);
            themeField.setForeground(t.getColor());
            keywordField.setForeground(t.getColor());
            themeField.setText(t.getName());
            keywordField.setText(t.getStringOfKeywords());
        }
        else{
            themeField.setText("");
            keywordField.setText("");
        }
        
    }//GEN-LAST:event_projectThemesListValueChanged
    
    private void deleteThemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteThemeButtonActionPerformed
        
        if(projectThemesList.getSelectedValue()!=null){
             int index=projectThemesArray.indexOf(projectThemesList.getSelectedValue());
             Theme t = projectThemesArray.get(index);
             projectThemesArray.remove(t);
        }
            PrintWriter outStream = null;
            try {
                outStream = new PrintWriter("themes.txt");
                projectListModel = new DefaultListModel();
                for(Theme th: projectThemesArray){
                    outStream.println(th.getStringForFile());
                    projectListModel.addElement(th);
                }
                outStream.close();
                projectThemesList.setModel(projectListModel);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(AnalyzerWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_deleteThemeButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        newThemeFrame.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveNewThemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNewThemeButtonActionPerformed
        Color col = JColorChooser.showDialog(newThemeFrame, "Choose Theme Color", Color.yellow);
        Theme theme = new Theme(newThemeText.getText());
        String[] keywords = newKeywordText.getText().split(",");
        for(String s: keywords){
            theme.addKeyword(new Keyword(s));
        }
        theme.setColor(col.getRGB());
        projectThemesArray.add(theme);
        projectListModel.addElement(theme);
        projectThemesList.setModel(projectListModel);
        
        PrintWriter outStream =null;
        //hardcoding file name
        try {
            outStream = new PrintWriter(new FileOutputStream("themes.txt",true));
            outStream.println(theme.getStringForFile());
            outStream.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AnalyzerWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveNewThemeButtonActionPerformed
    /**
     * Loop over each element in the selected themes list, and use the themes 
     * document to add the appropriate keywords. 
     */
    private void acceptThemesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptThemesButtonActionPerformed
        Object[] selected = selectedListModel.toArray();
        ArrayList<Theme> toSet = new ArrayList<Theme>();
        for(Object c: selected){
            Theme t = projectThemesArray.get(projectThemesArray.indexOf(c));
            toSet.add(t);
        }
        //setThemes is used instead of adding each theme individually to avoid
        //themes from previous analyses being reused
        analyzer.setThemes(toSet);
        themeManager.setVisible(false);
    }//GEN-LAST:event_acceptThemesButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fileNotFoundException.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void editThemeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editThemeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editThemeTextActionPerformed

    private void editThemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editThemeButtonActionPerformed
        if(projectThemesList.getSelectedValue()!=null){
             int index=projectThemesArray.indexOf(projectThemesList.getSelectedValue());
             final Theme t = projectThemesArray.get(index);
             
             editThemeText.setForeground(t.getColor());
             editKeywordsText.setForeground(t.getColor());
             editThemeText.setText(t.getName());
             editKeywordsText.setText(t.getStringOfKeywords());
             
             editThemeFrame.setVisible(true);
             
             saveChangesButton.addActionListener(new ActionListener(){
                    public void actionPerformed(ActionEvent e){
                           t.setName(editThemeText.getText());
                           t.setKeywords(makeKeywordsFromTextField(editKeywordsText.getText()));
                           Color c = JColorChooser.showDialog(null, "Choose a new color", t.getColor());
                           t.setColor(c.getRGB());
                        try {
                            rewriteThemesFile();
                        } catch (FileNotFoundException ex) {
                            Logger.getLogger(AnalyzerWindow.class.getName()).log(Level.SEVERE, null, ex);
                            }   
                        }
                }
             );
        }
    }//GEN-LAST:event_editThemeButtonActionPerformed

    private void saveChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesButtonActionPerformed
        
    }//GEN-LAST:event_saveChangesButtonActionPerformed
    private ArrayList<Keyword> makeKeywordsFromTextField(String k){
        String[] keys = k.split(",");
        ArrayList<Keyword> toReturn = new ArrayList<Keyword>();
        
        for(String s: keys){
            toReturn.add(new Keyword(s));
        }
        return toReturn;
    }
    private void rewriteThemesFile() throws FileNotFoundException{
        PrintWriter outStream = new PrintWriter("themes.txt");
        for(Theme t: projectThemesArray)
            outStream.println(t.getStringForFile());
        outStream.close();
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalyzerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalyzerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalyzerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalyzerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalyzerWindow().setVisible(true);
            }
        });
    }
    private Analyzer analyzer;
    private DefaultListModel selectedListModel = new DefaultListModel();
    private DefaultListModel projectListModel = new DefaultListModel();
    private ArrayList<Theme> projectThemesArray;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptThemesButton;
    private javax.swing.JButton analyzeButton;
    private javax.swing.JTextField analyzeFiles;
    private javax.swing.JLabel analyzeLabel;
    private javax.swing.JButton browseButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelChangesButton;
    private javax.swing.JButton deleteThemeButton;
    private javax.swing.JTextField editKeywordsText;
    private javax.swing.JButton editThemeButton;
    private javax.swing.JFrame editThemeFrame;
    private javax.swing.JTextField editThemeText;
    private javax.swing.JLabel error1;
    private javax.swing.JLabel error2;
    private javax.swing.JDialog fileNotFoundException;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel keyLabel;
    private javax.swing.JTextField keywordField;
    private javax.swing.JLabel keywordsLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField newKeywordText;
    private javax.swing.JButton newThemeButton;
    private javax.swing.JFrame newThemeFrame;
    private javax.swing.JTextField newThemeText;
    private javax.swing.JButton okErrorButton;
    private javax.swing.JFileChooser openFileChooser;
    private javax.swing.JTextField outputFile;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JLabel projectThemes;
    private javax.swing.JList projectThemesList;
    private javax.swing.JLabel reminderLabel;
    private javax.swing.JButton removeButtonTheme;
    private javax.swing.JButton saveChangesButton;
    private javax.swing.JButton saveNewThemeButton;
    private javax.swing.JButton selectThemeButton;
    private javax.swing.JLabel selectedThemes;
    private javax.swing.JList selectedThemesList;
    private javax.swing.JTextField themeField;
    private javax.swing.JFrame themeManager;
    private javax.swing.JLabel themeNameLabel;
    private javax.swing.JButton themesButton;
    private javax.swing.JDialog themesMissing;
    // End of variables declaration//GEN-END:variables
}